version: '3.8'
services:
  pact-broker:
    image: pactfoundation/pact-broker
    environment:
      PACT_BROKER_DATABASE_ADAPTER: postgresql
      PACT_BROKER_DATABASE_NAME: pact_broker
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: postgres
      PACT_BROKER_DATABASE_HOST: postgres
    ports:
      - "9292:9292"
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pact_broker
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.1
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:6.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_CREATE_TOPICS: "messages:1:1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
  consumer:
    build: ./consumer
    image: consumer-service
    command: npm run start
    ports:
      - "3000:3000"
    depends_on:
      - kafka
      - pact-broker
      - mongodb
    environment:
      PACT_BROKER_BASE_URL: http://pact-broker
      PACT_BROKER_USERNAME: pactbrokeruser
      PACT_BROKER_PASSWORD: pactbrokerpassword
      KAFKA_HOST: kafka:9092
      KAFKA_TOPIC: messages
  provider:
    build: ./provider
    image: provider-service
    command: npm run start
    ports:
      - "3001:3001"
    depends_on:
      - kafka
      - pact-broker
    environment:
      PACT_BROKER_BASE_URL: http://pact-broker
      PACT_BROKER_USERNAME: pactbrokeruser
      PACT_BROKER_PASSWORD: pactbrokerpassword
      KAFKA_HOST: kafka:9092
      KAFKA_TOPIC: messages